### ISSUE TITLE
Bug in ids of documents on dashboard

### ISSUE THREAD

**Issue by vikas-lb** [qdrant/qdrant-web-ui#122] opened 2023-10-24 07:00 UTC
Hi - I have created the ID of the document using the following hash function.
 
`record_id, _ = mmh3.hash64(file_data, signed=False)`

If I check the ID using Python client, I get the actual ID. On Qdrant dashboard, it seems that we approximate the value to the nearest thousand
Suppose the actual id is 298631332630714982. On UI, we get ID 298631332630715000 
It makes it slightly challenging to use the qdrant dashboard using record_id.

**Comment by generall** [comment] 2023-10-24 08:13
duplicate of https://github.com/qdrant/qdrant-web-ui/issues/87

**Closed** 2024-03-09 20:30 UTC
Labels: duplicate
